import turtle
def V ():
    turtle.down()
    turtle.left(90)
    turtle.forward(70)
    turtle.right(135)
    turtle.forward(50)
    turtle.right(135)
    turtle.forward(35)
    turtle.left(135)
    turtle.forward(50)
    turtle.right(135)
    turtle.forward(35)
def C ():
    turtle.right(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(50)
    turtle.up()
    turtle.right(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.down()
    turtle.forward(50)

turtle.reset()
turtle.up()
turtle.goto(-50,0)
V()
turtle.up()
turtle.goto(50,0)
turtle.down()
C()
